language: node_js
node_js:
  - 12.14.1

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
